<?php
$lang['f_moto'] = 'myacico.co.id menjamin kualitas toko kami melalui 5 poin berikut ini:';
$lang['f_guarantee1'] = '<p><b>Gratis Pengiriman</b><br>Kami akan mengirimkan pesanan anda secara cuma-cuma untuk area Jakarta</p>';
$lang['f_guarantee2'] = '<p><b>Keamanan Pembayaran</b><br>Kami akan memastikan kerahasiaan informasi pembayaran Anda.</p>';
$lang['f_guarantee3'] = '<p><b>Kemudahan Transaksi</b><br>Anda bisa melakukan transaksi dengan mudah melalui berbagai metode pembayaran</p>';
$lang['f_guarantee4'] = '<p><b>Garansi Produk Terpercaya</b><br>Produk yang Anda beli dapat diservice di berbagai outlet terpercaya</p>';
$lang['f_guarantee5'] = '<p><b>Layanan cepat</b><br>Customer service kami akan selalu cepat dan tanggap dalam memberikan informasi</p>';
$lang['footer_info'] = '<b>myacico.co.id, E-commerce Terlengkap & Terpercaya Dengan Beragam Produk Pilihan Serta Promo Menarik</b><br> Sebagai Toko Online baru di Indonesia, myacico.co.id yang memiliki slogan “Total Shopping Experience” hadir dengan delapan kategori pilihan untuk memenuhi kebutuhan Anda, mulai dari kebutuhan komputer, gadget, komunikasi, audio dan visual, mekanikal-elektrikal, hobi, perlengkapan rumah dan perlengkapan kantor. Bagi Anda yang memiliki kebutuhan laptop bisnis, laptop gaming, laptop murah, smartphone selfie, dan smartphone murah,  Toko Online myacico.co.id dapat memenuhi kebutuhan Anda denga menghadirkan berbagai varian laptop dan gadget terbaru dan terpopuler di kategori laptop & kategori gadget. Selain itu, Online Shop myacico.co.id juga menghadirkan kategori Komunikasi, Audio-Visual dan Hobi untuk memberikan pilihan produk lifestyle kekinian.<br><br>
Bagi Anda yang membutuhkan produk-produk maknikal-elektrikal, Toko Online MyACICO membantu Anda untuk memiliki perlengkapan mekanik-elektrik secara mudah dengan penawaran produk mekanikal terlengkap, mulai dari produk Bor, Genset, dan Gerinda. Berbagai produk perlengkapan rumah tangga juga hadir di Online Shop myacico.co.id, mulai dari produk elektronik rumah tangga,  seperti AC, perlatan dapur, kulkas, kompor, perlengkapan menjahit, perlengkapan mencuci, perlengkapan sanitasi, peralatan kebersihan dan barang konsumsi rumah tangga. Ditambah dengan varian perlengkapan kantor mulai dari  mebel kantor, perlengkapan seni, pengarsipan dokumen, buku, printer label, smart access, aksesoris meja kantor, kalkulator, mesin absen, kertas, shredder , mesin jilid & laminasi, papan tulis dan peralatan kasir. Ayo belanja online kebutuhan sehari-hari Anda di online shop myacico.co.id dengan kategori terlengkap dan terpecaya. Rasakan “Total Shopping Experience” Anda dengan menjelajahi kategori dengan ribuan produk pilihan di online shop myacico.co.id!
<br><br><b>Gratis Ongkir untuk Area Jakarta</b><br> Toko Online myacico.co.id memberikan Anda kemudahan dalam belanja online dengan memudahkan pengiriman produk yang anda pesan untuk pemesanan wilayah Jakarta. Nikmati belanja online untuk segala kebutuhan di Toko Online myacico.co.id setiap hari dengan promo-promo pilihan. Dapatkan harga spesial dengan mengunjungi website myacico.co.id. Promo spesial bagi pengunjung dapat dilihat pada website myacico.co.id dengan produk-produk terbaik yang ditawarkan Setiap hari, Anda juga masih bisa menikmati produk gadget termurah dengan Potongan harga terbaik, setiap hari.<br><br>

<b>Pengiriman 2-7 Hari Kerja</b><br> Sebagai toko online dengan kategori produk dan promo terlengkap, myacico.co.id juga menjamin pengiriman cepat untuk setiap produk yang di pesan. Komitmen  Toko Online myacico.co.id untuk dapat mengirimkan produk pelanggan dengan jangka waktu pengiriman 2-7 Hari Kerja. Pengiriman produk dari myacico.co.id akan di support oleh myACICO courrier, Ninja Express dan JNE.<br><br>
<b>Harga yang Kompetitif</b><br> myacico.co.id memberikan harga yang paling kompetitif kepada para costumer, sehingga costumer dapat merasakan pembelian produk laptop murah, gadget murah, tablet murah, kamera murah, drone murah,headset murah, game murah, Ac murah. Pembayaran dalam belanja online di myacico.co.id bisa Anda lakukan dengan bergam cara yang mudah. Pembayaran yang tersedia di Toko Online myacico.co.id, seperti pembayaran melalui Visa, MasterCard, CIMB Clicks, Mandiri Clickpay, dan Klik BCA.<br><br>
<b>Garansi 7 Hari Pengembalian Barang</b><br> Toko Online myacico.co.id sangat nyaman dan terpercaya. Online Shop myacico.co.id mendukung Anda agar nyaman dalam belanja, dengan garansi 7 hari pengembalian barang di myacico.co.id anda tidak perlu khawatir dengan kondisi barang yang anda pesan. Penggantian barang yang mengalami cacat produksi di tanggung oleh myacico.co.id dengan gratis pengiriman produk pada saat pengembalian, Anda bisa hubungi kami melalui Customer Care (telepon, email, dan live chat) yang online 24 jam untuk membantu Anda';
?>
